### ISSUE TITLE
Remove step 3 of this plugin

### ISSUE THREAD

**Issue by aviggiano** [matt-filion/serverless-external-s3-event#52] opened 2018-04-18 14:29 UTC
Hello,

First of all, thank you for creating this plugin. It is really a bummer that CloudFormation/serverless cannot attach events to existing buckets. 

I was wondering, however, if it the step 3 of this plugin could be removed by integrating with other hooks/scripting plugins. For example, [see this](https://github.com/mvila/serverless-plugin-scripts). I am not sure if it is possible, but if there was a way to automatically `s3Deploy`, without having to manually run that command, that would be awesome. At least for me, I don't bother too much about having to run step 1 (npm install), but I find it very annoying to change the way I deploy my functions. 

Please let me know if this makes sense. If it does, I can try submitting a PR (although I have never worked with serverless plugins before)

**Comment by matt-filion** [comment] 2019-02-25 19:56
Duplicate of #77

**Closed by matt-filion** 2019-02-25 19:56 UTC
